version: '3.8'

services:
  nexus:
    image: ${NEXUS_IMAGE}
    container_name: nexus
    restart: unless-stopped
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
        volume:
          nocopy: true
    ports:
      - "${NEXUS_PORT}:8081"
      - "5000:5000"
    networks:
      - nexus
      - proxy

networks:
  nexus:
    external: true

volumes:
  nexus-data:
    driver_opts:
      type: nfs
      o: addr=YOUR_NFS_SERVER_IP,nolock,soft,rw
      device: :/<NFS_SHARE_PATH>
